[profile.default]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
ffi = false
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]
